# Generated by Django 3.1 on 2021-01-27 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('funcionarios_que_atenderam', models.ManyToManyField(through='biblioteca.Emprestimo', to='biblioteca.Funcionario')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('localizacao', models.TextField()),
                ('nome_autor', models.ManyToManyField(to='biblioteca.Autor')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.leitor')),
                ('livros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
        ),
        migrations.AddField(
            model_name='leitor',
            name='livros_emprestados',
            field=models.ManyToManyField(related_name='livros_emprestimo', through='biblioteca.Emprestimo', to='biblioteca.Livro'),
        ),
        migrations.AddField(
            model_name='leitor',
            name='livros_reservados',
            field=models.ManyToManyField(related_name='livros_emprestados', through='biblioteca.Reserva', to='biblioteca.Livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='funcionarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.funcionario'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.leitor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro'),
        ),
    ]
