# Generated by Django 3.1 on 2021-01-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitor',
            name='funcionarios_que_atenderam',
        ),
        migrations.RemoveField(
            model_name='leitor',
            name='livros_emprestados',
        ),
        migrations.RemoveField(
            model_name='leitor',
            name='livros_reservados',
        ),
    ]
