# Generated by Django 3.1 on 2021-01-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20210127_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nome_autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='nome_autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
            preserve_default=False,
        ),
    ]
